### ISSUE TITLE
Softlayer DAL (US) IPv6 test fails

### ISSUE THREAD

**Issue by miyurusankalpa** [n-st/nench#6]
Connection to speedtest.dal01.softlayer.com over IPv6 fails.

```
--2019-07-19 14:22:21--  http://speedtest.dal01.softlayer.com/
Resolving speedtest.dal01.softlayer.com (speedtest.dal01.softlayer.com)... 2607:f0d0:1003:31::2
Connecting to speedtest.dal01.softlayer.com (speedtest.dal01.softlayer.com)|2607:f0d0:1003:31::2|:80... failed: Resource temporarily unavailable.
Retrying.
```

is it okay if i change the test to a another DC with working IPv6? 

- speedtest.dal05.softlayer.com
- speedtest.dal06.softlayer.com
- speedtest.dal09.softlayer.com

**Comment by n-st** [comment]
Thank you for pointing this out.
I was hesitant to change the URL, since this might impact comparability with older test runs.
But since I can't find a support contact for non-customers, and the problem doesn't seem to be temporary, the only short-term fix will indeed be to switch to a different DC…
I've run a short test and DAL06 seems to have the most consistent connection at the moment, so I've changed the URL to that.

Do let me know if you notice any further problems.
I also welcome suggestions for other providers, perhaps for an eventual switch away from Softlayer.

**Comment by n-st** [comment]
By the way, for future reference:
- Softlayer has an (older?) list of "public cloud" data centers [here](http://www.softlayer.com/node/2737).
- The old [bench.sh](https://freevps.us/bench.sh) uses dal05.softlayer for IPv4 tests and switches to dallas.linode for IPv6. There may or may not be a background behind that choice; I don't know for sure.
